//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace ssembassy_ankara.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class embassy_address
    {
        public string address { get; set; }
        [Key]
        public string telephone { get; set; }
        public string email { get; set; }
        public string fax { get; set; }
    }
}
