//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ssembassy_ankara.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class @event
    {
        public int id { get; set; }
        public string title { get; set; }
        public System.DateTime date { get; set; }
        public string description { get; set; }
        public string image_source { get; set; }
        public int category_id { get; set; }
    
        public virtual event_category event_category { get; set; }
    }
}
