//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace ssembassy_ankara.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class former_personel
    {
        [Key]
        public string personel_id { get; set; }
        public string title { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string telefon { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
    }
}
