//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ssembassy_ankara.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportantNotice
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string MessageEn { get; set; }
        public string MessageTr { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public bool Status { get; set; }
    }
}
