//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ssembassy_ankara.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineVisaApplication
    {
        public int Id { get; set; }
        public string ApplicationPlace { get; set; }
        public System.DateTime ApplicationDate { get; set; }
        public bool PreviouslyApplied { get; set; }
        public string PreviousVisaNo { get; set; }
        public Nullable<System.DateTime> PrevIssueDate { get; set; }
        public string PrevIssuePlace { get; set; }
        public Nullable<System.DateTime> PrevArrivalDate { get; set; }
        public string PrevEntryPoint { get; set; }
        public string PrevExitPoint { get; set; }
        public int VisaTypeId { get; set; }
        public int PurposeOfVisitId { get; set; }
        public int DurationOfStay { get; set; }
        public System.DateTime IntendedArrivalDate { get; set; }
        public int TransportModeId { get; set; }
        public string Surname { get; set; }
        public string GivenNames { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string CountryOfBirth { get; set; }
        public int GenderId { get; set; }
        public string MaritalStatus { get; set; }
        public string Nationality { get; set; }
        public int PassportTypeId { get; set; }
        public string PassportNumber { get; set; }
        public System.DateTime PassportDateOfIssue { get; set; }
        public string PassportCountryOfIssue { get; set; }
        public System.DateTime PassportExpiryDate { get; set; }
        public string PassportPlaceOfIssue { get; set; }
        public string PresentOccupation { get; set; }
        public string OccupationTitle { get; set; }
        public string EmployerName { get; set; }
        public string EmployerAddress { get; set; }
        public string EmployerPhone { get; set; }
        public string EmployerEmail { get; set; }
        public string ApplicantPresentAddress { get; set; }
        public string ApplicantPermanentCountryAddress { get; set; }
        public string ApplicantPhone { get; set; }
        public string ApplicantMobile { get; set; }
        public string ApplicantEmail { get; set; }
        public string SpouseSurname { get; set; }
        public string SpouseGivenNames { get; set; }
        public string SpousePermanentAddress { get; set; }
        public string SpousePhone { get; set; }
        public string SpouseMobile { get; set; }
        public string SpouseEmail { get; set; }
        public string KinSurname { get; set; }
        public string KinGivenNames { get; set; }
        public string KinPermanentAddress { get; set; }
        public string KinPhone { get; set; }
        public string KinMobile { get; set; }
        public string KinEmail { get; set; }
        public bool BeenConvicted { get; set; }
        public bool BeenDeportedForViolationOfLaw { get; set; }
        public bool DrugOffence { get; set; }
        public bool CommittedTrafficking { get; set; }
        public bool InfectiousOrContagiousDisease { get; set; }
        public string ExplanationIfYes { get; set; }
        public string PlaceOfStayAddress { get; set; }
        public string FundsAvailableForStay { get; set; }
        public string ReferenceName { get; set; }
        public string ReferencePhone { get; set; }
        public string ReferenceAddress { get; set; }
        public Nullable<System.DateTime> ReferenceBirthDate { get; set; }
        public Nullable<int> ReferenceGenderId { get; set; }
        public string ReferenceRelationshipToApplicant { get; set; }
        public string ReferenceProfession { get; set; }
        public string ReferenceNationality { get; set; }
        public string BirthPlace { get; set; }
    
        public virtual PassportType PassportType { get; set; }
        public virtual PurposeOfVisit PurposeOfVisit { get; set; }
        public virtual Sex Sex { get; set; }
        public virtual VisaTypeRequested VisaTypeRequested { get; set; }
        public virtual Sex Sex2 { get; set; }
    }
}
