//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ssembassy_ankara.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personel
    {
        public string personel_id { get; set; }
        public int position_id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string telefon { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public System.DateTime contract_start { get; set; }
        public System.DateTime contract_end { get; set; }
        public string img_url { get; set; }
        public string gender { get; set; }
    
        public virtual positions positions { get; set; }
    }
}
