//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ssembassy_ankara.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisaApproval
    {
        public int OfficerId { get; set; }
        public int ApplicantId { get; set; }
        public string OfficerName { get; set; }
        public string Title { get; set; }
        public string EntryType { get; set; }
        public int PeriodOfStay { get; set; }
        public System.DateTime DateOfApproval { get; set; }
        public string Comments { get; set; }
        public double VisaFee { get; set; }
        public System.DateTime DateOfReceipt { get; set; }
        public string ReceiptNo { get; set; }
        public string DesignatedOfficerName { get; set; }
        public string DesignatedOfficerTitle { get; set; }
    
        public virtual OnlineVisaApplication OnlineVisaApplication { get; set; }
    }
}
